name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566

      - name: Run unit tests
        run: task test

      - name: Build luarocks artifact
        run: task

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tn-${{ github.sha }}.all.rock
          path: "build/output/tn-${{ github.sha }}.all.rock"
